In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [19]:
from sklearn.datasets import make_classification

In [20]:
x,y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_classes=2, random_state=1)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

#**HyperParameter Tuning:**

###**Grid Search CV and Random Search CV:**

In [23]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

###**Grid Search CV:**

In [32]:
params = {
    'penalty': ['l1', 'l2', 'elasticnet'],
    'C': [1, 2, 10, 20, 30, 40],
    'solver': ['saga'],
    'l1_ratio': [0, 0.5, 1]
}


In [33]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [1, 2, 10, 20, 30, 40],
 'solver': ['saga'],
 'l1_ratio': [0, 0.5, 1]}

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
classifier = LogisticRegression()

In [36]:
classifier

LogisticRegression()

In [37]:
clf = GridSearchCV(classifier, param_grid=params, cv=5,verbose = 2)

In [38]:
clf

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40], 'l1_ratio': [0, 0.5, 1],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['saga']},
             verbose=2)

In [39]:
clf.fit(x_train, y_train)

Fitting 5 folds for each of 54 candidates, totalling 270 fits
[CV] END ...........C=1, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l1, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END ...........C=1, l1_ratio=0, penalty=l2, solver=saga; total time=   0.0s
[CV] END ...C=1, l1_ratio=0, penalty=elasticnet, solver=saga; total time=   0.0s
[CV] END ...C=1, l1_ratio=0, penalty=elasticnet

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 10, 20, 30, 40], 'l1_ratio': [0, 0.5, 1],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['saga']},
             verbose=2)

In [40]:
clf.best_params_

{'C': 1, 'l1_ratio': 0, 'penalty': 'l1', 'solver': 'saga'}

In [41]:
clf.best_score_

np.float64(0.8028571428571428)

In [42]:
clf.best_estimator_.predict(x_test)

array([0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [43]:
model = LogisticRegression(C=1,penalty='l2')

In [44]:
model

LogisticRegression(C=1)

In [45]:
model.fit(x_train, y_train)

LogisticRegression(C=1)

In [46]:
y_pred = model.predict(x_test)

In [47]:
y_pred

array([0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0])

In [48]:
model.predict_proba(x_test)

array([[0.9327426 , 0.0672574 ],
       [0.01587499, 0.98412501],
       [0.3607235 , 0.6392765 ],
       [0.91100619, 0.08899381],
       [0.93608983, 0.06391017],
       [0.65164431, 0.34835569],
       [0.0717141 , 0.9282859 ],
       [0.03193548, 0.96806452],
       [0.92395637, 0.07604363],
       [0.98063739, 0.01936261],
       [0.45013353, 0.54986647],
       [0.80070245, 0.19929755],
       [0.86590034, 0.13409966],
       [0.53971613, 0.46028387],
       [0.43844051, 0.56155949],
       [0.1673668 , 0.8326332 ],
       [0.9104726 , 0.0895274 ],
       [0.91788312, 0.08211688],
       [0.01248191, 0.98751809],
       [0.54877535, 0.45122465],
       [0.73164465, 0.26835535],
       [0.84306107, 0.15693893],
       [0.87447267, 0.12552733],
       [0.8925803 , 0.1074197 ],
       [0.8371179 , 0.1628821 ],
       [0.78100273, 0.21899727],
       [0.79958272, 0.20041728],
       [0.44816402, 0.55183598],
       [0.81313503, 0.18686497],
       [0.03763234, 0.96236766],
       [0.

In [49]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [50]:
print(accuracy_score(y_test, y_pred))

0.83


In [51]:
print(confusion_matrix(y_test, y_pred))

[[127  15]
 [ 36 122]]


In [52]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.89      0.83       142
           1       0.89      0.77      0.83       158

    accuracy                           0.83       300
   macro avg       0.83      0.83      0.83       300
weighted avg       0.84      0.83      0.83       300



###**Randomized Search CV:**

In [53]:
from sklearn.model_selection import RandomizedSearchCV

In [54]:
r_clf = RandomizedSearchCV(classifier, param_distributions=params,n_iter=10, cv=5)

In [55]:
r_clf

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 10, 20, 30, 40],
                                        'l1_ratio': [0, 0.5, 1],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['saga']})

In [56]:
r_clf.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 2, 10, 20, 30, 40],
                                        'l1_ratio': [0, 0.5, 1],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['saga']})

In [57]:
r_clf.best_params_

{'solver': 'saga', 'penalty': 'l1', 'l1_ratio': 1, 'C': 30}

In [58]:
r_clf.best_score_

np.float64(0.8014285714285714)

# **Now we can Simply build a ML model!**

### Or Simply use the best_estimator_